spring:
  data:
    mongodb:
      database: stockserver
      host: localhost
      port: 27017
      username: rootuser
      password: rootpass
      authentication-database: admin

server:
  servlet:
    context-path: /api